import type { Metadata } from "next";
import localFont from "next/font/local";
import { Cairo } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const monadi = localFont({
  src: "./fonts/ArbFONTS-Monadi.ttf",
  variable: "--font-monadi",
});

const avenir = localFont({
  src: "./fonts/AvenirLTProMedium.otf",
  variable: "--font-avenir",
});

const cairo = Cairo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "الورم الليفي",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${monadi.variable} ${avenir.variable} ${cairo.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
